basePath: /task-management-service
definitions:
  dto.CreateTaskRequest:
    properties:
      assignee_id:
        type: string
      description:
        type: string
      due_date:
        type: string
      title:
        type: string
    type: object
  dto.Task:
    properties:
      assignee_id:
        type: string
      created_at:
        type: string
      creator_id:
        type: string
      description:
        type: string
      due_date:
        type: string
      id:
        type: string
      status:
        type: string
      title:
        type: string
      update_at:
        type: string
    type: object
  dto.Tasks:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.Task'
        type: array
    type: object
  dto.UpdateTaskRequest:
    properties:
      assignee_id:
        type: string
      description:
        type: string
      due_date:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  model.AuthenticationRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.AuthenticationResponse:
    properties:
      access_token:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  model.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  model.CreateUserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Task Management App Swagger APIs.
  title: Task Management Service APIs
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Authentication
      parameters:
      - description: User Authentication JSON
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.AuthenticationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthenticationResponse'
      summary: Authentication
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: Create User JSON
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.CreateUserResponse'
      summary: Create new user
      tags:
      - auth
  /v1/task:
    get:
      consumes:
      - application/json
      description: Get list all task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Tasks'
            type: array
      security:
      - BearerAuth: []
      summary: Get list all task
      tags:
      - task
    post:
      consumes:
      - application/json
      description: Create Task
      parameters:
      - description: create task request
        in: body
        name: CreateTaskRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/dto.Task'
            type: array
      security:
      - BearerAuth: []
      summary: Create Task
      tags:
      - task
  /v1/task/{id}:
    delete:
      consumes:
      - application/json
      description: Delete task by given id (uuid)
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: Delete task by given id
      tags:
      - task
    get:
      consumes:
      - application/json
      description: Get task by given Id
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Task'
            type: array
      security:
      - BearerAuth: []
      summary: Get task by given Id
      tags:
      - task
    patch:
      consumes:
      - application/json
      description: Update task by given Id
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: string
      - description: update task request
        in: body
        name: UpdateTaskRequest
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Task'
            type: array
      security:
      - BearerAuth: []
      summary: Update task by given Id
      tags:
      - task
  /v1/task/today:
    get:
      consumes:
      - application/json
      description: Get list all task due date by today
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Tasks'
            type: array
      security:
      - BearerAuth: []
      summary: Get list all task due date by today
      tags:
      - task
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
